version: '3'
services:
  flight-srv:
    command: --registry_address=registry:8500 --server_address=0.0.0.0:9090 --transport=tcp 
    image: go-micro-tech-talk/flight
    networks:
      - gomicrotechtalk_go-micro-tech-talk
    external_links:
    - registry
    - rabbitmq
    - nats
    - elasticsearch
    expose:
      - "9090"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200

  flight-api:
    command: --registry_address=registry:8500 --server_address=0.0.0.0:9090 --transport=tcp 
    image: go-micro-tech-talk/flight-api
    networks:
      - gomicrotechtalk_go-micro-tech-talk
    external_links:
    - registry
    expose:
      - "9090"

  orchestrator-srv:
    command: --registry_address=registry:8500 --server_address=0.0.0.0:9090 --broker=nats --broker_address=nats:4222 --transport=grpc
    image: go-micro-tech-talk/orchestrator
    networks:
      - gomicrotechtalk_go-micro-tech-talk
    external_links:
    - registry
    - rabbitmq
    - nats
    expose:
      - "9090"

  indexer-srv_1:
    command: --registry_address=registry:8500 --server_address=0.0.0.0:9090 --broker=nats --broker_address=nats:4222 --transport=grpc
    image: go-micro-tech-talk/indexer
    networks:
      - gomicrotechtalk_go-micro-tech-talk
    external_links:
    - registry
    - rabbitmq
    - nats
    - elasticsearch
    expose:
      - "9090"
    #deploy:
      #mode: replicated
      #replicas: 2
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200

  indexer-srv_2:
    command: --registry_address=registry:8500 --server_address=0.0.0.0:9090 --broker=nats --broker_address=nats:4222 --transport=tcp
    image: go-micro-tech-talk/indexer
    networks:
      - gomicrotechtalk_go-micro-tech-talk
    external_links:
    - registry
    - rabbitmq
    - nats
    - elasticsearch
    expose:
      - "9090"
    #deploy:
      #mode: replicated
      #replicas: 2
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200      

  static-server:
    image: go-micro-tech-talk/static-server
    hostname: "static-server"
    networks:
      - gomicrotechtalk_go-micro-tech-talk
    ports:
      - "4004:80"
      
networks:
  gomicrotechtalk_go-micro-tech-talk:
    external: true    