// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/Rakanixu/go-micro-tech-talk/flight/srv/proto/flight/flight.proto

/*
Package proto_flight is a generated protocol buffer package.

It is generated from these files:
	github.com/Rakanixu/go-micro-tech-talk/flight/srv/proto/flight/flight.proto

It has these top-level messages:
	ReadRequest
	ReadResponse
	SearchRequest
	SearchResponse
	HealthRequest
	HealthResponse
*/
package proto_flight

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ReadRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index" json:"index,omitempty"`
	Id    string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
}

func (m *ReadRequest) Reset()                    { *m = ReadRequest{} }
func (m *ReadRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()               {}
func (*ReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ReadRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *ReadRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadResponse struct {
	Result string `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *ReadResponse) Reset()                    { *m = ReadResponse{} }
func (m *ReadResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()               {}
func (*ReadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ReadResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type SearchRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index" json:"index,omitempty"`
	Id    string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SearchRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *SearchRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type SearchResponse struct {
	Result string `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *SearchResponse) Reset()                    { *m = SearchResponse{} }
func (m *SearchResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()               {}
func (*SearchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SearchResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type HealthRequest struct {
}

func (m *HealthRequest) Reset()                    { *m = HealthRequest{} }
func (m *HealthRequest) String() string            { return proto.CompactTextString(m) }
func (*HealthRequest) ProtoMessage()               {}
func (*HealthRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type HealthResponse struct {
	Info string `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
}

func (m *HealthResponse) Reset()                    { *m = HealthResponse{} }
func (m *HealthResponse) String() string            { return proto.CompactTextString(m) }
func (*HealthResponse) ProtoMessage()               {}
func (*HealthResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *HealthResponse) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func init() {
	proto.RegisterType((*ReadRequest)(nil), "proto.flight.ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "proto.flight.ReadResponse")
	proto.RegisterType((*SearchRequest)(nil), "proto.flight.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "proto.flight.SearchResponse")
	proto.RegisterType((*HealthRequest)(nil), "proto.flight.HealthRequest")
	proto.RegisterType((*HealthResponse)(nil), "proto.flight.HealthResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Service service

type ServiceClient interface {
	Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error)
	Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...client.CallOption) (*HealthResponse, error)
}

type serviceClient struct {
	c           client.Client
	serviceName string
}

func NewServiceClient(serviceName string, c client.Client) ServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "proto.flight"
	}
	return &serviceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *serviceClient) Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Service.Read", in)
	out := new(ReadResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Service.Search", in)
	out := new(SearchResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) Health(ctx context.Context, in *HealthRequest, opts ...client.CallOption) (*HealthResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Service.Health", in)
	out := new(HealthResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Service service

type ServiceHandler interface {
	Read(context.Context, *ReadRequest, *ReadResponse) error
	Search(context.Context, *SearchRequest, *SearchResponse) error
	Health(context.Context, *HealthRequest, *HealthResponse) error
}

func RegisterServiceHandler(s server.Server, hdlr ServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Service{hdlr}, opts...))
}

type Service struct {
	ServiceHandler
}

func (h *Service) Read(ctx context.Context, in *ReadRequest, out *ReadResponse) error {
	return h.ServiceHandler.Read(ctx, in, out)
}

func (h *Service) Search(ctx context.Context, in *SearchRequest, out *SearchResponse) error {
	return h.ServiceHandler.Search(ctx, in, out)
}

func (h *Service) Health(ctx context.Context, in *HealthRequest, out *HealthResponse) error {
	return h.ServiceHandler.Health(ctx, in, out)
}

func init() {
	proto.RegisterFile("github.com/Rakanixu/go-micro-tech-talk/flight/srv/proto/flight/flight.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 279 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x50, 0xd1, 0x4a, 0xc3, 0x30,
	0x14, 0x5d, 0xcb, 0xac, 0x78, 0xdd, 0x2a, 0x04, 0x91, 0x59, 0x7d, 0x90, 0x20, 0xb2, 0x97, 0xb6,
	0xe0, 0xf0, 0xd9, 0x27, 0x41, 0xf0, 0xad, 0xfb, 0x82, 0x2c, 0xbd, 0x6b, 0xc3, 0xba, 0x66, 0x26,
	0xe9, 0xd8, 0xa7, 0xfa, 0x39, 0x62, 0xd2, 0x42, 0x3b, 0x06, 0xb2, 0xa7, 0x9b, 0x7b, 0x4e, 0xce,
	0xb9, 0xf7, 0x5c, 0xf8, 0x2a, 0x84, 0x29, 0x9b, 0x55, 0xc2, 0xe5, 0x36, 0xcd, 0xd8, 0x86, 0xd5,
	0xe2, 0xd0, 0xa4, 0x85, 0x8c, 0xb7, 0x82, 0x2b, 0x19, 0x1b, 0xe4, 0x65, 0x6c, 0x58, 0xb5, 0x49,
	0xd7, 0x95, 0x28, 0x4a, 0x93, 0x6a, 0xb5, 0x4f, 0x77, 0x4a, 0x1a, 0xd9, 0x01, 0xae, 0x24, 0x16,
	0x23, 0x13, 0x5b, 0x12, 0x87, 0xd1, 0x05, 0x5c, 0x67, 0xc8, 0xf2, 0x0c, 0xbf, 0x1b, 0xd4, 0x86,
	0xdc, 0xc2, 0x85, 0xa8, 0x73, 0x3c, 0xcc, 0xbc, 0x27, 0x6f, 0x7e, 0x95, 0xb9, 0x86, 0x84, 0xe0,
	0x8b, 0x7c, 0xe6, 0x5b, 0xc8, 0x17, 0x39, 0x7d, 0x81, 0x89, 0x13, 0xe9, 0x9d, 0xac, 0x35, 0x92,
	0x3b, 0x08, 0x14, 0xea, 0xa6, 0x32, 0xad, 0xac, 0xed, 0xe8, 0x1b, 0x4c, 0x97, 0xc8, 0x14, 0x2f,
	0xcf, 0xb3, 0x9f, 0x43, 0xd8, 0xc9, 0xfe, 0x19, 0x70, 0x03, 0xd3, 0x4f, 0x64, 0x95, 0xe9, 0x06,
	0xd0, 0x67, 0x08, 0x3b, 0xa0, 0x95, 0x12, 0x18, 0x8b, 0x7a, 0x2d, 0x5b, 0xa1, 0x7d, 0xbf, 0xfe,
	0x78, 0x70, 0xb9, 0x44, 0xb5, 0x17, 0x1c, 0xc9, 0x3b, 0x8c, 0xff, 0xb2, 0x90, 0xfb, 0xa4, 0x7f,
	0x97, 0xa4, 0x77, 0x94, 0x28, 0x3a, 0x45, 0x39, 0x7b, 0x3a, 0x22, 0x1f, 0x10, 0xb8, 0x6d, 0xc9,
	0xc3, 0xf0, 0xdf, 0x20, 0x7a, 0xf4, 0x78, 0x9a, 0xec, 0xdb, 0xb8, 0xcd, 0x8f, 0x6d, 0x06, 0x01,
	0x8f, 0x6d, 0x86, 0x61, 0xe9, 0x68, 0x15, 0x58, 0x7a, 0xf1, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xc3,
	0xcd, 0x91, 0xa5, 0x33, 0x02, 0x00, 0x00,
}
